
cd function/random && npm publish -s && npm owner add knolleary
cd ../../function/rbe && npm publish -s && npm owner add knolleary
cd ../../function/smooth && npm publish -s && npm owner add knolleary
cd ../../social/notify && npm publish -s && npm owner add knolleary
cd ../../social/pushbullet && npm publish -s && npm owner add knolleary
#cd ../../social/snapchat && npm publish -s && npm owner add knolleary
cd ../../social/irc && npm publish -s && npm owner add knolleary
cd ../../social/pushover && npm publish -s && npm owner add knolleary
cd ../../social/twitter && npm publish -s && npm owner add knolleary
cd ../../social/xmpp && npm publish -s && npm owner add knolleary
#cd ../../social/pusher && npm publish -s && npm owner add knolleary
cd ../../social/dweetio && npm publish -s && npm owner add knolleary
cd ../../social/prowl && npm publish -s && npm owner add knolleary
cd ../../social/nma && npm publish -s && npm owner add knolleary
cd ../../social/twilio && npm publish -s && npm owner add knolleary
cd ../../hardware/blink1 && npm publish -s && npm owner add knolleary
cd ../../hardware/HummingboardGPIO && npm publish -s && npm owner add knolleary
cd ../../hardware/blinkstick && npm publish -s && npm owner add knolleary
cd ../../hardware/LEDborg && npm publish -s && npm owner add knolleary
cd ../../hardware/sensorTag && npm publish -s && npm owner add knolleary
#cd ../../hardware/scanBLE && npm publish -s && npm owner add knolleary
#cd ../../hardware/hue && npm publish -s && npm owner add knolleary
cd ../../hardware/Arduino && npm publish -s && npm owner add knolleary
cd ../../hardware/BBB && npm publish -s && npm owner add knolleary
cd ../../hardware/PiFace && npm publish -s && npm owner add knolleary
cd ../../hardware/makey && npm publish -s && npm owner add knolleary
cd ../../hardware/Pibrella && npm publish -s && npm owner add knolleary
cd ../../hardware/digiRGB && npm publish -s && npm owner add knolleary
cd ../../hardware/wemo && npm publish -s && npm owner add knolleary
cd ../../hardware/heatmiser && npm publish -s && npm owner add knolleary
cd ../../hardware/PiLiter && npm publish -s && npm owner add knolleary
cd ../../parsers/msgpack && npm publish -s && npm owner add knolleary
cd ../../parsers/base64 && npm publish -s && npm owner add knolleary
cd ../../parsers/geohash && npm publish -s && npm owner add knolleary
cd ../../parsers/what3words && npm publish -s && npm owner add knolleary
cd ../../storage/sqlite && npm publish -s && npm owner add knolleary
cd ../../storage/mongodb && npm publish -s && npm owner add knolleary
cd ../../storage/mysql && npm publish -s && npm owner add knolleary
cd ../../storage/leveldb && npm publish -s && npm owner add knolleary
cd ../../storage/redis && npm publish -s && npm owner add knolleary
cd ../../time/suncalc && npm publish -s && npm owner add knolleary
cd ../../utility/exif && npm publish -s && npm owner add knolleary
cd ../../utility/daemon && npm publish -s && npm owner add knolleary
cd ../../io/emoncms && npm publish -s && npm owner add knolleary
#cd ../../io/mqlight/&& npm publish -s && npm owner add knolleary
cd ../../io/mdns && npm publish -s && npm owner add knolleary
cd ../../io/stomp && npm publish -s && npm owner add knolleary
cd ../../io/ping && npm publish -s && npm owner add knolleary
cd ../../io/wol && npm publish -s && npm owner add knolleary
cd ../../io/serialport && npm publish -s && npm owner add knolleary
cd ../../io/snmp && npm publish -s && npm owner add knolleary
cd ../../analysis/wordpos && npm publish -s && npm owner add knolleary
cd ../../analysis/swearfilter && npm publish -s && npm owner add knolleary
