#!/bin/bash

python_cmd='python3'
# Fallback to Python 2, if Python 3 is not available
command -v python3 > /dev/null || python_cmd='python'

BASEDIR=$(dirname $0)
$python_cmd -u $BASEDIR/nrgpio.py $@
